name: noval
description: A new Flutter project.

# Prevent the package from being accidentally published to pub.dev
publish_to: "none" 

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.0.7
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icha.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icha.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/ah.jpg
    - assets/gatsby.jpg
    - assets/harry.jpg
    - assets/images.jpg
    - assets/mocking.png
    - assets/pride.jpg
    - assets/rye.jpg
    - assets/sapiens.jpg
